In [1]:
import pandas as pd
import numpy as np

In [2]:
# Question 1p

# What's the version of Pandas that you installed?

# You can get the version information using the __version__ field:

In [3]:
pd.__version__

'1.5.3'

In [4]:
# Getting the data

# For this homework, we'll use the California Housing Prices dataset. Download it from here.

# You can do it with wget:

# wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

# Or just open it with your browser and click "Save as...".
# read it with Pandas.

In [11]:
data = pd.read_csv("housing.csv")

In [6]:
# Question 2

# How many columns are in the dataset?
#    10

In [7]:
data

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

In [12]:
data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [14]:
data['total_bedrooms'].sum()

10990309.0

In [15]:
# Question 3

# Which columns in the dataset have missing values?
# total_bedrooms

In [16]:
print(data.isnull().sum())

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64


In [17]:
# Question 4
# Number of unique values in the 'ocean_proximity' column
# 5

In [18]:
unique=data['ocean_proximity'].unique()
print(unique)

['NEAR BAY' '<1H OCEAN' 'INLAND' 'NEAR OCEAN' 'ISLAND']


In [19]:
# Question 5
# Average value of the 'median_house_value' for the houses near the bay

In [20]:
near_bay_data = data[data['ocean_proximity'] == 'NEAR BAY']
mean_house_value_near_bay = near_bay_data['median_house_value'].mean()
mean_house_value_near_bay

259212.31179039303

In [21]:
# The average of total_bedrooms

In [22]:
data['total_bedrooms'].mean()

537.8705525375618

In [23]:
# Question 6

#    Calculate the average of total_bedrooms column in the dataset.
#    Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
#    Now, calculate the average of total_bedrooms again.
#    Has it changed? NO


In [24]:
data['total_bedrooms'].fillna(538)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [25]:
data['total_bedrooms'].mean()

537.8705525375618

In [26]:
# Select all the options located on islands.
# Select only columns housing_median_age, total_rooms, total_bedrooms.
# Get the underlying NumPy array. Let's call it X.

In [27]:
island_data = data[data['ocean_proximity'] == 'ISLAND']
selected_columns = island_data[['housing_median_age', 'total_rooms', 'total_bedrooms']]
X=np.array(selected_columns)
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [28]:
# To get the transpose, use X.T

In [29]:
TX = X.T
TX

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [30]:
# Compute matrix-matrix multiplication between the transpose of X and X
XTX=np.dot(TX, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [31]:
# Compute the inverse of XTX.
inverse_XTX = np.linalg.inv(XTX)
inverse_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [32]:
# Create an array y
y = np.array([950, 1300, 800, 1000, 1300])

In [33]:
# Multiply the inverse of XTX with the transpose of X
result = np.dot(inverse_XTX, TX)
result

array([[-0.00825608, -0.00653208, -0.00232159,  0.02565144,  0.01204934],
       [-0.00165852,  0.0011141 ,  0.00139656, -0.00103215, -0.00110698],
       [ 0.00754365, -0.00301964, -0.00455125,  0.00181685,  0.00329418]])

In [34]:
#  multiply the result by y
w = np.dot(result, y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [35]:
# # Access the last element of w
last_element = w[-1]
print(last_element)

5.699229455065574
